// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoS1ZR5ON5FE_M5ajYnbUQcLDmmLF5RxI',
    appId: '1:838115257641:web:f4f9ed2aa8838483c31b38',
    messagingSenderId: '838115257641',
    projectId: 'carrentaldb-e1bf9',
    authDomain: 'carrentaldb-e1bf9.firebaseapp.com',
    databaseURL: 'https://carrentaldb-e1bf9-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldb-e1bf9.appspot.com',
    measurementId: 'G-BK6CBP9VPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZziTqJ0-30GK69tpzIDoh9sj1q-E67k',
    appId: '1:838115257641:android:fc457de6f121ddf4c31b38',
    messagingSenderId: '838115257641',
    projectId: 'carrentaldb-e1bf9',
    databaseURL: 'https://carrentaldb-e1bf9-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldb-e1bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBOPS0sEO1osrC62REuLfVnznbhkvk_M',
    appId: '1:838115257641:ios:4ace8556ea28cc3cc31b38',
    messagingSenderId: '838115257641',
    projectId: 'carrentaldb-e1bf9',
    databaseURL: 'https://carrentaldb-e1bf9-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldb-e1bf9.appspot.com',
    iosBundleId: 'com.example.rentCars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBOPS0sEO1osrC62REuLfVnznbhkvk_M',
    appId: '1:838115257641:ios:4ace8556ea28cc3cc31b38',
    messagingSenderId: '838115257641',
    projectId: 'carrentaldb-e1bf9',
    databaseURL: 'https://carrentaldb-e1bf9-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldb-e1bf9.appspot.com',
    iosBundleId: 'com.example.rentCars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoS1ZR5ON5FE_M5ajYnbUQcLDmmLF5RxI',
    appId: '1:838115257641:web:3ffeccde46a3798ac31b38',
    messagingSenderId: '838115257641',
    projectId: 'carrentaldb-e1bf9',
    authDomain: 'carrentaldb-e1bf9.firebaseapp.com',
    databaseURL: 'https://carrentaldb-e1bf9-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldb-e1bf9.appspot.com',
    measurementId: 'G-VZCLD0WTDZ',
  );
}
